{
 "title": "METEOR  - Dasboard",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jvm_classes_loaded_classes{application=~\"$application\"}, instance)"
   },
   { "name": "application", "query": "label_values(application)" }
  ]
 },
 "panels": [
  {
   "title": "Nb requête période",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{application=~\"$application\", instance=~\"$instance\",status=\"200\", uri=~\".*compute.*|.*export.*\"})"
    }
   ]
  },
  {
   "title": "Up time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_uptime_seconds{application=\"$application\"}"
    }
   ]
  },
  {
   "title": "Nb requete sur periode",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 5, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{application=~\"$application\", instance=~\"$instance\",status=\"200\", uri=~\".*compute.*|.*export.*\"}) by (uri)",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Temps moyen",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 5, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_sum{application=\"$application\", status=\"200\",uri=~\".*compute.*|.*export.*\"}) by(uri) / sum(http_server_requests_seconds_count{application=\"$application\", status=\"200\", uri=~\".*compute.*|.*export.*\"}) by(uri)",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "system_load_average_1m",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load_average_1m{application=\"$application\"}"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 2 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "CPU système",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 2 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(system_cpu_usage{application=\"$application\"})*100"
    }
   ]
  },
  {
   "title": "Non heap used",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 7 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{application=\"$application\"}*1000"
    }
   ]
  },
  {
   "title": "Requetes administration",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{application=~\"$application\", instance=~\"$instance\",status=\"200\", uri=~\".*auth.*|.*admin.*|.*stripe.*\"}) by (uri)",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Temps moyen authent",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 12 },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_sum{application=\"$application\", status=\"200\",uri=~\".*auth.*|.*admin.*|.*stripe.*\"}) by(uri) / sum(http_server_requests_seconds_count{application=\"$application\", status=\"200\", uri=~\".*auth.*|.*admin.*|.*stripe.*\"}) by(uri)",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Status code",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 5, "x": 10, "y": 12 },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{application=~\"$application\", instance=~\"$instance\", uri!~\".*actuator.*\"}) by (status)",
     "legendFormat": "status {{status}}"
    }
   ]
  },
  {
   "title": "Méthodes",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 12 },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{application=~\"$application\", instance=~\"$instance\", uri!~\".*actuator.*\"}) by (method, status)",
     "legendFormat": "{{method}} - {{status}}"
    }
   ]
  },
  {
   "title": "status - method",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{application=~\"$application\", instance=~\"$instance\", uri!~\".*actuator.*\"})  by (application, status, method)",
     "legendFormat": "{{method}}({{status}})"
    }
   ]
  },
  {
   "title": "Status requete / endpoint",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{application=~\"$application\", instance=~\"$instance\", uri!~\".*actuator.*\"}",
     "legendFormat": "{{uri}} - {{status}} - {{method}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\"})"
    }
   ]
  }
 ]
}